version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  build:
    docker:
      - image: softcover/softcover
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: specs
          command: bundle exec rspec -f d
